import { bars, missingBars, comparison, trend, missingTrend, histogram, branching,
  comparisonPreview, trendPreview, histogramPreview, branchingPreview } from './graph-examples.mjs';

export const charts = [
  {
    slug: 'bar-chart', name: 'Bar chart', label: 'Compare quantities', group: 'Figures & graphs',
    description: 'Rank categories by magnitude, with aligned names, exact values, and a shared zero baseline.',
    story: 'components-bar-chart--callers',
    api: [
      ['.bars / .bar-row', 'A semantic list and its rows. Wide lists align labels, bars, and values; narrow lists put the bar below the text.'],
      ['.bar-label / .bar-value / .bar-note', 'The category, exact quantity with units, and optional qualification. Long names wrap; numbers stay together.'],
      ['.bar-track / .bar-fill', 'The common scale and proportional mark. Set --dd-bar to value / shared maximum × 100%. Use one maximum for the entire list.'],
      ['.bar-track.is-missing', 'An unavailable measurement. Omit bar-fill and write “Not measured” in bar-value. A measured zero uses --dd-bar:0%.'],
      ['.tone-*', 'Optional category identity. The visible category name must carry the same identity without color.'],
    ],
    note: 'Use for non-negative category magnitudes. Always start bars at zero and state the maximum and units. Never give a tiny value a minimum visual width or normalize each bar separately. Use Meter for shares of one whole; a table for precise lookup. Values and labels remain in HTML when printing or using assistive technology.',
    examples: [{title:'Compare callers on one scale',html:bars},{title:'A measured zero and an unknown',html:missingBars}],
  },
  {
    slug: 'comparison-plot', name: 'Comparison plot', label: 'Compare two observations', group: 'Figures & graphs',
    description: 'Show a before-and-after difference on one axis, with both endpoints and denominators visible.',
    story: 'components-comparison-plot--coverage',
    preview: comparisonPreview,
    api: [
      ['.draw-wrap / .draw', 'A scrolling wrapper and fixed-size SVG. Set --dd-draw-width to the viewBox width in px; author coordinates at that size.'],
      ['.plot-axis / .plot-grid', 'The axis and supporting guides. State the domain and units with draw-note text.'],
      ['.plot-span', 'The connector between two observations of the same measure. It expresses a difference, not a measured trajectory.'],
      ['.plot-before / .plot-point', 'Hollow before marker and filled after marker. Both need direct labels and exact values.'],
      ['.draw-value / .draw-note / .plate-source', 'Numeric labels, supporting type, and the snapshot or measurement conditions.'],
    ],
    note: 'Use a dumbbell for paired observations. Map x = left + (value − minimum) / (maximum − minimum) × plot width, using the same domain for every row. Include zero for percentage coverage. Name changes in denominator and use percentage points for the difference between percentages. For signed changes, keep decreases neutral unless they represent a problem; red is reserved for warnings and absence.',
    examples: [{title:'A change with a different denominator',html:comparison}],
  },
  {
    slug: 'line-plot', name: 'Line plot', label: 'Follow an ordered measure', group: 'Figures & graphs',
    description: 'Trace a measure across time or position while keeping gaps and observation boundaries explicit.',
    story: 'components-line-plot--cumulative',
    preview: trendPreview,
    api: [
      ['.draw-wrap / .draw', 'Fixed-size SVG in a scrolling region. Add tabindex="0", role="region", and an accessible name when it scrolls.'],
      ['.plot-line / .plot-point', 'An authored path and its observations. Straight segments interpolate; horizontal and vertical segments form a step plot.'],
      ['.plot-line-alt / .plot-point-alt', 'A dashed line and hollow points for a secondary series. Pair with direct series names; color alone is insufficient.'],
      ['.plot-missing / .plot-missing-label', 'A dashed missing interval and its visible explanation. Do not draw a connecting path across it.'],
      ['.plot-axis / .plot-grid / .draw-note', 'Numeric axes, guides and unit labels; coordinate spacing must reflect the data domain.'],
    ],
    note: 'Use a numeric, ordered horizontal domain, not category rank. Map y = bottom − (value − minimum) / (maximum − minimum) × plot height. Label a nonzero axis minimum explicitly. Use steps for counts that change at events; avoid smoothing that implies unobserved values. Split paths around missing samples, and retain isolated points. Include exact observations in a table or caption. The example uses source position, not invented timestamps.',
    examples: [{title:'Discrete accumulation as a step plot',html:trend},{title:'An unrecorded interval stays open',html:missingTrend}],
  },
  {
    slug: 'histogram', name: 'Histogram', label: 'Read a distribution', group: 'Figures & graphs',
    description: 'Show how observations fall into numeric bins, including empty intervals and sample size.',
    story: 'components-histogram--callers',
    preview: histogramPreview,
    api: [
      ['.draw-wrap / .draw', 'A fixed-size SVG. Narrow containers scroll without reducing label sizes.'],
      ['.plot-bin', 'An interval’s rectangle. Use adjacent equal-width bins on a count axis and start heights at zero.'],
      ['.plot-zero', 'An observed empty bin remains on the axis with an explicit zero label.'],
      ['.plot-axis / .plot-grid / .draw-value', 'Axis, guides and exact bin counts. Label both axes and the bin boundary convention.'],
      ['.plate / .plate-source', 'Caption, sample size, selection criteria and data source.'],
    ],
    note: 'Use a histogram for numeric distribution and Bar chart for named categories. Keep all bins in numeric order, including zeros. Equal-width bins allow counts; unequal widths require frequency density so area represents frequency. State inclusive or half-open boundaries and the observed sample size. Missing observations are excluded with an explicit count, never inserted as zeros; when none were measured, use Empty. This six-caller example describes one table, not the entire project.',
    examples: [{title:'Equal-width bins with observed zeros',html:histogram}],
  },
  {
    slug: 'flow-graph', name: 'Flow graph', label: 'Explain a branch', group: 'Figures & graphs',
    description: 'Make a decision, its branches, and their outcomes readable without relying on color.',
    story: 'components-flow-graph--reading-mode',
    preview: branchingPreview,
    api: [
      ['.draw-wrap / .draw', 'The fixed-size diagram and its scrolling region; use draw text roles and explicit SVG alignment attributes.'],
      ['.node-action / .node-decision / .node-terminal', 'An action rectangle, a decision diamond, and an outcome. All share one node size and a 1.5px outline; shape identifies the role.'],
      ['.edge-flow / .edge-arrow', 'Connector paths and open arrowheads. Draw these before nodes so lines cannot cross the node labels.'],
      ['.edge-label', 'A plain branch label. Route connectors clear of the text; do not paint a background halo around letters. Use with draw-label.'],
      ['.draw-label / .draw-strong / .draw-note', 'Node names and explanatory text at the shared drawing type size.'],
    ],
    note: 'Use for processes with choices or branches. Choose one node module for the whole figure: the full example uses 224 × 64px, 48px between rows, and 8px between arrow tips and their targets. Center every node title with draw-strong; place supporting notes outside the boxes. The index uses 96 × 40px nodes and shorter labels at the same text size. If a label needs more room, enlarge the shared module rather than one node. Put a visible condition on every branch. The generator computes coordinates and routes; this component does not run a layout engine. Graph is for dependencies; Composition’s ordered flow is for an unbranched reading sequence.',
    examples: [{title:'Choose a reading mode',html:branching}],
  },
];
