import { html } from "./helpers.js";

export default {
  title: "Layouts/Doc shell",
  parameters: {
    docs: {
      description: {
        component:
          "A sidebar you navigate from, a bar that says where you are, and a " +
          "column you read. For anything generated per-symbol or per-record, " +
          "where a reader arrives at one page out of hundreds and needs to know " +
          "immediately what else is here.\n\n" +
          "The genre is one wrapper element rather than a class on `<body>`, so " +
          "a frame can be nested without the layout depending on where it sits.",
      },
    },
  },
};

const sidebar = `
  <nav class="sidebar">
    <div class="sb-head"><a class="sb-site" href="#">owner/repo</a></div>
    <div class="sb-block">
      <p class="sb-title">Browse</p>
      <ul class="sb-list">
        <li class="is-active"><a href="#">Overview</a></li>
        <li><a href="#">Statements</a><span class="sb-count">844</span></li>
        <li><a href="#">Tables</a><span class="sb-count">12</span></li>
        <li><a href="#">Findings</a><span class="sb-count">978</span></li>
      </ul>
    </div>
    <div class="sb-block">
      <p class="sb-title">On this page</p>
      <ul class="sb-list sb-context">
        <li><a href="#one">First heading</a></li>
        <li data-dd-level="3"><a href="#two">A heading under it</a></li>
        <li><a href="#three">Second heading</a></li>
      </ul>
    </div>
  </nav>`;

const topbar = `
  <header class="topbar">
    <button class="btn btn-quiet nav-toggle" data-dd-nav-toggle title="Toggle navigation">☰</button>
    <nav class="crumbs">
      <a href="#">Overview</a><span class="crumb-sep">/</span><span class="crumb-current">Tables</span>
    </nav>
    <div class="topbar-tools">
      <input type="search" class="field-input field-search" placeholder="Search… ( / )" data-dd-search>
      <button class="btn btn-quiet" data-dd-theme-toggle title="Toggle theme">◐</button>
    </div>
  </header>
  <div class="search-results" data-dd-search-results hidden></div>`;

/** The whole frame. Resize the preview below 900px to see the sidebar leave
 *  the flow — it stays in the DOM in its reading order, so a screen reader and
 *  a keyboard still reach it in the same place. */
export const Frame = {
  render: () => html`
    <div class="doc">
      ${sidebar}
      <div class="main">
        ${topbar}
        <main class="content">
          <h1>Tables<span class="count">12</span></h1>
          <p class="lede">Which statements read, write or alter a table, and where each is issued.</p>
          <h2 id="one">First heading<a class="anchor" href="#one">§</a></h2>
          <p>A catalog heading is a label on a band of rows, not a statement, so it is
             a rule across the column rather than something large enough to read as a title.</p>
          <h3 id="two">A heading under it<a class="anchor" href="#two">§</a></h3>
          <p>Scroll, and the sidebar tracks which of these you are reading.</p>
          <h2 id="three">Second heading<a class="anchor" href="#three">§</a></h2>
          <p style="min-height:60vh">Room to scroll.</p>
        </main>
        <footer class="doc-footer">Generated by <a href="#">the thing that generated it</a></footer>
      </div>
    </div>`,
};

/** Without a sidebar — a single generated page that has nowhere else to go. */
export const NoSidebar = {
  render: () => html`
    <div class="doc">
      <div class="main">
        ${topbar}
        <main class="content">
          <h1>One page on its own</h1>
          <p class="lede">The frame still supplies the reading column, the heading scale
             and the bar; it simply has no navigation to offer.</p>
        </main>
      </div>
    </div>`,
};
